apiVersion: v1
kind: Service
metadata:
  name: retainiq-api-service
  namespace: retainiq-system
  labels:
    app.kubernetes.io/name: retainiq-api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: retainiq-api
