apiVersion: v1
kind: Secret
metadata:
  name: retainiq-secrets
  namespace: retainiq-system
  labels:
    app.kubernetes.io/name: retainiq
type: Opaque
stringData:
  API_KEY: "prod-secret-retainiq-key-2026"
  OPENAI_API_KEY: "mock-openai-key-prod"
  GEMINI_API_KEY: "mock-gemini-key-prod"
